create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 2 and 120),
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  timezone text not null default 'America/Los_Angeles',
  base_city text,
  base_state text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.organization_members (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'dispatcher', 'technician', 'accountant')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table public.customers (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_type text not null default 'residential' check (customer_type in ('residential', 'commercial')),
  first_name text,
  last_name text,
  company_name text,
  email text,
  phone text,
  preferred_contact text check (preferred_contact in ('phone', 'sms', 'email')),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  check (first_name is not null or last_name is not null or company_name is not null)
);

create table public.properties (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  label text not null default 'Primary property',
  address_line_1 text not null,
  address_line_2 text,
  city text not null,
  state text not null,
  postal_code text not null,
  latitude numeric(9, 6),
  longitude numeric(9, 6),
  access_notes text,
  safety_notes text,
  panel_location text,
  panel_manufacturer text,
  service_amperage integer check (service_amperage is null or service_amperage > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create table public.technicians (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  display_name text not null,
  phone text,
  color text not null default '#FFBF18',
  start_location_type text not null default 'shop' check (start_location_type in ('shop', 'home', 'custom')),
  end_location_type text not null default 'shop' check (end_location_type in ('shop', 'home', 'custom', 'none')),
  skills text[] not null default '{}',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create table public.jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete set null,
  property_id uuid references public.properties(id) on delete set null,
  technician_id uuid references public.technicians(id) on delete set null,
  job_number bigint generated by default as identity,
  status text not null default 'draft' check (status in ('draft', 'awaiting_payment', 'confirmed', 'needs_review', 'assigned', 'en_route', 'arrived', 'in_progress', 'completed', 'canceled', 'no_show', 'rescheduled')),
  category text not null default 'diagnostic',
  priority text not null default 'standard' check (priority in ('standard', 'emergency', 'after_hours')),
  customer_description text,
  ai_summary text,
  safety_flags text[] not null default '{}',
  scheduled_start timestamptz,
  scheduled_end timestamptz,
  arrival_window_start timestamptz,
  arrival_window_end timestamptz,
  route_locked boolean not null default false,
  diagnostic_fee_cents integer not null default 10000 check (diagnostic_fee_cents >= 0),
  diagnostic_paid boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  check (scheduled_end is null or scheduled_start is null or scheduled_end > scheduled_start),
  unique (organization_id, job_number)
);

create table public.blackout_periods (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  technician_id uuid not null references public.technicians(id) on delete cascade,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  block_type text not null default 'hard' check (block_type in ('hard', 'flexible', 'private')),
  reason text,
  recurrence_rule text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table public.service_settings (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null unique references public.organizations(id) on delete cascade,
  diagnostic_fee_cents integer not null default 10000,
  diagnostic_minutes integer not null default 60,
  credit_diagnostic_to_repair boolean not null default true,
  cancellation_fee_cents integer not null default 5000,
  free_reschedule_hours integer not null default 24,
  emergency_fee_cents integer not null default 20000,
  after_hours_fee_cents integer not null default 15000,
  automatic_booking_radius_miles integer not null default 50,
  standard_pricing_radius_miles integer not null default 50,
  minimum_travel_buffer_minutes integer not null default 15,
  operational_buffer_minutes integer not null default 10,
  payment_required_to_confirm boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.estimates (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  job_id uuid references public.jobs(id) on delete set null,
  estimate_number bigint generated by default as identity,
  status text not null default 'draft' check (status in ('draft', 'sent', 'approved', 'declined', 'expired')),
  subtotal_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, estimate_number)
);

create table public.invoices (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  job_id uuid references public.jobs(id) on delete set null,
  invoice_number bigint generated by default as identity,
  status text not null default 'draft' check (status in ('draft', 'sent', 'partially_paid', 'paid', 'overdue', 'void')),
  subtotal_cents integer not null default 0,
  diagnostic_credit_cents integer not null default 0,
  tax_cents integer not null default 0,
  total_cents integer not null default 0,
  balance_due_cents integer not null default 0,
  due_at timestamptz,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, invoice_number)
);

create table public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  sku text,
  name text not null,
  category text,
  unit text not null default 'each',
  quantity_on_hand numeric(12, 2) not null default 0,
  reorder_point numeric(12, 2) not null default 0,
  unit_cost_cents integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz,
  unique (organization_id, sku)
);

create table public.activity_events (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  actor_user_id uuid references auth.users(id) on delete set null,
  event_type text not null,
  label text not null,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create index organization_members_user_id_idx on public.organization_members(user_id);
create index customers_org_name_idx on public.customers(organization_id, last_name, first_name);
create index properties_org_customer_idx on public.properties(organization_id, customer_id);
create index technicians_org_active_idx on public.technicians(organization_id, is_active);
create index jobs_org_schedule_idx on public.jobs(organization_id, scheduled_start) where archived_at is null;
create index jobs_technician_schedule_idx on public.jobs(technician_id, scheduled_start) where archived_at is null;
create index blackout_periods_technician_time_idx on public.blackout_periods(technician_id, starts_at, ends_at);
create index estimates_org_status_idx on public.estimates(organization_id, status);
create index invoices_org_status_idx on public.invoices(organization_id, status);
create index inventory_org_stock_idx on public.inventory_items(organization_id, quantity_on_hand);
create index activity_events_org_created_idx on public.activity_events(organization_id, created_at desc);

create function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_updated_at() from public, anon, authenticated;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'organizations', 'organization_members', 'customers', 'properties',
    'technicians', 'jobs', 'blackout_periods', 'service_settings',
    'estimates', 'invoices', 'inventory_items'
  ]
  loop
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end;
$$;

create function private.is_org_member(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.organization_members membership
      where membership.organization_id = target_organization_id
        and membership.user_id = (select auth.uid())
    );
$$;

create function private.is_org_admin(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.organization_members membership
      where membership.organization_id = target_organization_id
        and membership.user_id = (select auth.uid())
        and membership.role in ('owner', 'admin')
    );
$$;

create function private.can_manage_members(target_organization_id uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select (select auth.uid()) is not null
    and (
      exists (
        select 1
        from public.organizations organization
        where organization.id = target_organization_id
          and organization.created_by = (select auth.uid())
      )
      or exists (
        select 1
        from public.organization_members membership
        where membership.organization_id = target_organization_id
          and membership.user_id = (select auth.uid())
          and membership.role in ('owner', 'admin')
      )
    );
$$;

revoke all on all functions in schema private from public, anon;
grant execute on function private.is_org_member(uuid) to authenticated;
grant execute on function private.is_org_admin(uuid) to authenticated;
grant execute on function private.can_manage_members(uuid) to authenticated;

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;

create policy "Members can view organizations"
on public.organizations for select
to authenticated
using ((select private.is_org_member(id)));

create policy "Users can create organizations"
on public.organizations for insert
to authenticated
with check (created_by = (select auth.uid()));

create policy "Admins can update organizations"
on public.organizations for update
to authenticated
using ((select private.is_org_admin(id)))
with check ((select private.is_org_admin(id)));

create policy "Owners can delete organizations"
on public.organizations for delete
to authenticated
using (
  exists (
    select 1 from public.organization_members membership
    where membership.organization_id = id
      and membership.user_id = (select auth.uid())
      and membership.role = 'owner'
  )
);

create policy "Members can view organization memberships"
on public.organization_members for select
to authenticated
using ((select private.is_org_member(organization_id)));

create policy "Admins can add organization members"
on public.organization_members for insert
to authenticated
with check ((select private.can_manage_members(organization_id)));

create policy "Admins can update organization members"
on public.organization_members for update
to authenticated
using ((select private.can_manage_members(organization_id)))
with check ((select private.can_manage_members(organization_id)));

create policy "Admins can remove organization members"
on public.organization_members for delete
to authenticated
using ((select private.can_manage_members(organization_id)));

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'customers', 'properties', 'technicians', 'jobs', 'blackout_periods',
    'service_settings', 'estimates', 'invoices', 'inventory_items', 'activity_events'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format(
      'create policy "Organization members can view %1$s" on public.%1$I for select to authenticated using ((select private.is_org_member(organization_id)))',
      table_name
    );
    execute format(
      'create policy "Organization members can add %1$s" on public.%1$I for insert to authenticated with check ((select private.is_org_member(organization_id)))',
      table_name
    );
    execute format(
      'create policy "Organization members can update %1$s" on public.%1$I for update to authenticated using ((select private.is_org_member(organization_id))) with check ((select private.is_org_member(organization_id)))',
      table_name
    );
    execute format(
      'create policy "Organization members can delete %1$s" on public.%1$I for delete to authenticated using ((select private.is_org_member(organization_id)))',
      table_name
    );
  end loop;
end;
$$;

revoke all on all tables in schema public from anon;
grant usage on schema public to authenticated;
grant select, insert, update, delete on all tables in schema public to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter default privileges in schema public revoke all on tables from anon;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public grant usage, select on sequences to authenticated;
